// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpBagPQvh0X2mTTnabZPo1HS_TdOsFNVA',
    appId: '1:70001102720:web:fbb502c3480fb2be4d7b65',
    messagingSenderId: '70001102720',
    projectId: 'lottery-app-16986',
    authDomain: 'lottery-app-16986.firebaseapp.com',
    storageBucket: 'lottery-app-16986.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpUd74LMIabnqVuf9qLcUsa4i37DJ0mqQ',
    appId: '1:70001102720:android:c4b0327effceb13c4d7b65',
    messagingSenderId: '70001102720',
    projectId: 'lottery-app-16986',
    storageBucket: 'lottery-app-16986.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu1iKSe5EW_wqtF404163j8XlNeCGGTLQ',
    appId: '1:70001102720:ios:3e989361b1b5e9b54d7b65',
    messagingSenderId: '70001102720',
    projectId: 'lottery-app-16986',
    storageBucket: 'lottery-app-16986.appspot.com',
    iosClientId: '70001102720-efo9virnfne6rtugd6aak9qtleakn28v.apps.googleusercontent.com',
    iosBundleId: 'com.instaflutter.freeloginscreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu1iKSe5EW_wqtF404163j8XlNeCGGTLQ',
    appId: '1:70001102720:ios:b6bfd7b3585429b14d7b65',
    messagingSenderId: '70001102720',
    projectId: 'lottery-app-16986',
    storageBucket: 'lottery-app-16986.appspot.com',
    iosClientId: '70001102720-80o4oj28sebov498nr66gfsa1j7nej13.apps.googleusercontent.com',
    iosBundleId: 'com.instaflutter.freeloginscreen.mac',
  );
}
