name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build_web:
    name: Build Flutter (Web)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
          channel: 'stable'
    - run: flutter pub get
    - run: flutter config --enable-web
    - run: flutter build web
    - name: Deploy to Firebase
      env:
        PROJECT_ID: lottery-app-16986
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_LOTTERY_APP_16986 }}
      run: |
        echo "$GOOGLE_APPLICATION_CREDENTIALS" > service-account-key.json
        npm install -g firebase-tools@latest
        firebase deploy --only hosting --public build/web