name: Build and Release app to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ''

      - name: Build Web App
        run: flutter build web -t lib/main.dart

      - name: Set up Google Cloud credentials
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_LOTTERY_APP_16986 }}
          project_id: lottery-app-16986  # Replace with your project ID

      - name: Deploy to Firebase Hosting
        run: |
          echo "$FIREBASE_SERVICE_ACCOUNT_LOTTERY_APP_16986" > keyfile.json
          gcloud auth activate-service-account --key-file=keyfile.json
          firebase use --lottery-app-16986
          firebase deploy --only hosting

